name: computables_flutter
description: The computables package with Flutter extensions.
version: 1.0.0
repository: https://github.com/danReynolds/computables
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  computables: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
